import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, symlinkSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { validateStagingAudioCanaryInput } from "../validate-staging-audio-canary-input.mjs";

const workflow = await readFile(new URL("../../../.github/workflows/staging-article-feedback-audio-canary.yml", import.meta.url), "utf8");
const validatorPath = fileURLToPath(new URL("../validate-staging-audio-canary-input.mjs", import.meta.url));

test("staging audio mining can run only by manual default-branch dispatch", () => {
  assert.match(workflow, /workflow_dispatch:/);
  assert.doesNotMatch(workflow, /schedule:/);
  assert.match(workflow, /Require the repository default branch/);
  assert.match(workflow, /environment: vibepub-staging/);
  assert.match(workflow, /vibepub-staging-deploy/);
  assert.match(workflow, /phase:[\s\S]*transcribe[\s\S]*start[\s\S]*revision/);
});

test("staging audio mining binds exact isolated resources and never receives Production WeChat credentials", () => {
  assert.match(workflow, /STAGING_RESOURCE_MANIFEST_JSON/);
  assert.match(workflow, /STAGING_PUBLIC_BASE_URL/);
  assert.match(workflow, /attest-staging-origin\.mjs --preflight/);
  assert.match(workflow, /attest-staging-origin\.mjs --fetch/);
  assert.match(workflow, /R2_BUCKET_NAME/);
  assert.match(workflow, /MINING_V3_HANDOFF_ENABLED: "true"/);
  assert.match(workflow, /CLEANUP_PERMANENT_AUDIO_FAILURES: "false"/);
  assert.match(workflow, /validate-staging-audio-canary-input\.mjs/);
  assert.doesNotMatch(workflow, /vibepub\.litianc\.cn|WECHAT_APP_ID|WECHAT_APP_SECRET|WECHAT_PROXY|GITHUB_PAT|FILES_TOKEN/);
});

test("accepts the hyphenated audio filenames generated by the Android app", () => {
  const userId = "usr_9281e2ef-edf4-49ab-b256-24fe0d8200dc";
  assert.equal(validateStagingAudioCanaryInput({
    PHASE: "transcribe",
    TARGET_KEY: `users/${userId}/inbox/VibePub-2026-08-30-073218-0m30s-Debug-Audio-Import.mp3`,
    USER_ID: userId,
    WORKSPACE_ID: "ws_9281e2ef-edf4-49ab-b256-24fe0d8200dc",
  }), true);
});

test("still rejects traversal and another user's audio", () => {
  const base = {
    PHASE: "transcribe",
    USER_ID: "usr_test-user",
    WORKSPACE_ID: "ws_test-workspace",
  };
  assert.equal(validateStagingAudioCanaryInput({
    ...base,
    TARGET_KEY: "users/usr_test-user/inbox/../private.mp3",
  }), false);
  assert.equal(validateStagingAudioCanaryInput({
    ...base,
    TARGET_KEY: "users/usr_other/inbox/VibePub-2026-08-30-073218-0m30s.mp3",
  }), false);
});

test("the real CLI accepts Android audio and rejects unsafe phase and revision inputs", () => {
  const userId = "usr_9281e2ef-edf4-49ab-b256-24fe0d8200dc";
  const baseEnv = {
    ...process.env,
    PHASE: "transcribe",
    TARGET_KEY: `users/${userId}/inbox/VibePub-2026-08-30-073218-0m30s-Debug-Audio-Import.mp3`,
    USER_ID: userId,
    WORKSPACE_ID: "ws_9281e2ef-edf4-49ab-b256-24fe0d8200dc",
    REVISION_REQUEST_KEY: "",
    RECORDING_ID: "",
    ARTICLE_ID: "",
    PARENT_VERSION_ID: "",
  };
  const run = overrides => spawnSync(process.execPath, [validatorPath], {
    env: { ...baseEnv, ...overrides },
    encoding: "utf8",
  });

  assert.equal(run({}).status, 0);
  assert.equal(run({ PHASE: "publish" }).status, 1);
  assert.equal(run({ PHASE: "revision" }).status, 1);
  assert.equal(run({
    PHASE: "revision",
    REVISION_REQUEST_KEY: "users/usr_other/revision-requests/12/request.json",
    RECORDING_ID: "12",
    ARTICLE_ID: `article_v3_${"1".repeat(64)}`,
    PARENT_VERSION_ID: `version_v3_${"2".repeat(64)}`,
  }).status, 1);
});

test("the CLI still validates when launched through a symbolic link", () => {
  const directory = mkdtempSync(join(tmpdir(), "vibepub-audio-validator-"));
  const linkedValidator = join(directory, "validator link.mjs");
  try {
    symlinkSync(validatorPath, linkedValidator);
    const result = spawnSync(process.execPath, [linkedValidator], {
      env: {
        ...process.env,
        PHASE: "unsafe",
        TARGET_KEY: "users/usr_test/inbox/audio.mp3",
        USER_ID: "usr_test",
        WORKSPACE_ID: "ws_test",
      },
      encoding: "utf8",
    });
    assert.equal(result.status, 1);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
});

test("transcribe and start phases require an exact safe handoff status", () => {
  assert.match(workflow, /set \+e[\s\S]*MINING_EXIT=\$\?[\s\S]*set -e/);
  assert.match(workflow, /if \[ "\$PHASE" != "transcribe" \]; then[\s\S]*exit "\$MINING_EXIT"/);
  assert.match(workflow, /staging-audio-canary-request\.mjs status/);
  assert.match(workflow, /EXPECTED_DECISION/);
  assert.match(workflow, /v3_pending_start/);
  assert.match(workflow, /accepted/);
  assert.match(workflow, /article_id/);
  assert.match(workflow, /run_id/);
  assert.match(workflow, /--workspace-id "\$WORKSPACE_ID"/);
  assert.match(workflow, /--minimum-transcript-created-at "\$CANARY_DEPLOYED_AT"/);
  assert.match(workflow, /if \[ "\$PHASE" = "transcribe" \]; then[\s\S]*FRESHNESS_ARGS/);
  assert.match(workflow, /source_hash/);
  assert.match(workflow, /recording_id/);
  assert.match(workflow, /candidate_commit=process\.env\.GITHUB_SHA/);
  assert.match(workflow, /manifest_hash=process\.env\.STAGING_MANIFEST_HASH/);
  assert.match(workflow, /STAGING_CANARY_EXPECTED_PARENT_VERSION_ID/);
  assert.match(workflow, /Wait for start to reach verified draft_ready/);
  assert.match(workflow, /editorial_status/);
  assert.match(workflow, /completed_agent_count/);
  assert.match(workflow, /v1_count/);
  assert.match(workflow, /wechat_draft_count/);
  assert.match(workflow, /CANARY_DEPLOYED_AT/);
  assert.match(workflow, /candidate_fresh/);
  assert.match(workflow, /Verify revision produced v2 and completed WeChat update/);
  assert.match(workflow, /revision_completed_count/);
  assert.match(workflow, /v2_count/);
  assert.match(workflow, /verify:revision-readback/);
  assert.match(workflow, /revision-readback-evidence\.json/);
  assert.match(workflow, /state\.wechat_readback=readback/);
  const bootstrapReadGate = workflow.indexOf("Open the exact bootstrap gate before reading an existing handoff");
  const existingHandoffRead = workflow.indexOf("Read the existing exact handoff before a full feedback phase");
  const fullGrant = workflow.indexOf("Build and verify the exact expiring feedback grant");
  assert.ok(bootstrapReadGate > 0 && existingHandoffRead > bootstrapReadGate && fullGrant > existingHandoffRead);
  const handoffReadGate = workflow.slice(bootstrapReadGate, existingHandoffRead);
  assert.match(handoffReadGate, /if: inputs\.phase != 'transcribe'/);
  assert.match(handoffReadGate, /build-bootstrap/);
  assert.match(handoffReadGate, /handoff-read-config\/main\.wrangler\.toml/);
  assert.match(handoffReadGate, /wrangler deploy --dry-run/);
  assert.match(handoffReadGate, /wrangler deploy --config/);
  assert.doesNotMatch(handoffReadGate, /image\.wrangler\.toml|wechat\.wrangler\.toml|MINING_V3_HANDOFF_TOKEN/);
  const refreshedBootstrap = handoffReadGate.lastIndexOf("build-bootstrap");
  const finalRender = handoffReadGate.lastIndexOf("staging-article-feedback-canary.mjs render");
  const finalVerify = handoffReadGate.lastIndexOf("staging-article-feedback-canary.mjs verify");
  const liveDeploy = handoffReadGate.lastIndexOf("wrangler deploy --config");
  assert.ok(refreshedBootstrap < finalRender && finalRender < finalVerify && finalVerify < liveDeploy);
});

test("every audio phase uses bounded grants and always restores the flag-off baseline", () => {
  assert.match(workflow, /timeout-minutes: 180/);
  assert.match(workflow, /Render the permanent flag-off rollback baseline first/);
  assert.match(workflow, /staging-article-feedback-canary\.mjs build-bootstrap/);
  assert.match(workflow, /staging-article-feedback-canary\.mjs build/);
  assert.match(workflow, /staging-article-feedback-canary\.mjs render/);
  assert.match(workflow, /staging-article-feedback-canary\.mjs verify/);
  const dryRun = workflow.indexOf('wrangler deploy --dry-run --config "$RUNNER_TEMP/canary-config/main.wrangler.toml"');
  const refresh = workflow.indexOf("Refresh the expiring grant after dry-run");
  const deploy = workflow.indexOf("Deploy the exact image canary configuration");
  assert.ok(dryRun > 0 && refresh > dryRun && deploy > refresh);
  assert.match(workflow, /wrangler deploy --dry-run --config "\$RUNNER_TEMP\/canary-config\/main\.wrangler\.toml"/);
  assert.match(workflow, /wrangler deploy --config "\$RUNNER_TEMP\/canary-config\/image\.wrangler\.toml"/);
  assert.match(workflow, /wrangler deploy --config "\$RUNNER_TEMP\/canary-config\/wechat\.wrangler\.toml"/);
  assert.match(workflow, /Close the exact-user main gate[\s\S]*if: always\(\)/);
  assert.match(workflow, /Remove the image canary configuration[\s\S]*if: always\(\)/);
  assert.match(workflow, /Remove the WeChat canary configuration[\s\S]*if: always\(\)/);
  assert.match(workflow, /Require all temporary grants to be closed[\s\S]*main-cleanup-deployed[\s\S]*image-cleanup-deployed[\s\S]*wechat-cleanup-deployed/);
  assert.match(workflow, /STAGING_FEEDBACK_CANARY_OPERATOR_RUN_ID:\$\{GITHUB_RUN_ID\}/);
  const mainDeploy = workflow.indexOf("Deploy the exact-user main canary gate");
  const imageDeploy = workflow.indexOf("Deploy the exact image canary configuration");
  assert.ok(mainDeploy > 0 && mainDeploy < imageDeploy);
  const closeMain = workflow.indexOf("Close the exact-user main gate");
  const removeImage = workflow.indexOf("Remove the image canary configuration");
  const removeWechat = workflow.indexOf("Remove the WeChat canary configuration");
  const removeMarker = workflow.indexOf("Remove the main cleanup marker");
  assert.ok(closeMain > 0 && closeMain < removeImage && removeImage < removeWechat && removeWechat < removeMarker);
  assert.match(workflow, /STAGING_FEEDBACK_CANARY_CLEANUP_MARKER_HASH/);
});

test("masks exact inputs and generated grant identities before Wrangler can log variables", () => {
  const inputMask = workflow.indexOf("Mask the exact synthetic inputs before any deployment");
  const grantMask = workflow.indexOf("Mask generated canary identities before rendering");
  const firstDryRun = workflow.indexOf('wrangler deploy --dry-run --config "$RUNNER_TEMP/canary-config/main.wrangler.toml"');
  assert.ok(inputMask > 0 && grantMask > inputMask && firstDryRun > grantMask);
  assert.match(workflow, /::add-mask::\$\{escape\(value\)\}/);
  assert.match(workflow, /feedback-canary-grant\.json[\s\S]*::add-mask::/);
  assert.match(workflow, /replace\(\/%\/g,"%25"\)/);
  assert.match(workflow, /replace\(\/\\r\/g,"%0D"\)/);
  assert.match(workflow, /replace\(\/\\n\/g,"%0A"\)/);
  assert.match(workflow, /> "\$RUNNER_TEMP\/mining-private\.log" 2>&1/);
  assert.doesNotMatch(workflow, /cat "\$RUNNER_TEMP\/mining-private\.log"/);
});

test("bounds Mining time and gives protected D1 checks both Cloudflare credentials", () => {
  assert.match(workflow, /timeout 1200s env PUBLIC_BASE_URL=/);
  assert.match(workflow, /timeout 300s env PUBLIC_BASE_URL=/);
  assert.match(workflow, /timeout 300s npm ci --prefix infra\/mining/);
  assert.match(workflow, /for attempt in \$\(seq 1 40\)/);
  assert.match(workflow, /for attempt in \$\(seq 1 20\)/);
  assert.match(workflow, /timeout 25s node infra\/staging\/query-staging-d1\.mjs/);
  assert.match(workflow, /QUERY_EXIT=\$\?/);
  assert.match(workflow, /"\$QUERY_EXIT" -eq 75/);
  assert.match(workflow, /"\$QUERY_EXIT" -eq 124/);
  assert.match(workflow, /test "\$QUERY_EXIT" -eq 0 \|\| exit "\$QUERY_EXIT"/);
  assert.match(workflow, /Staging D1 read failed temporarily/);
  const startCheck = workflow.match(/- name: Wait for start to reach verified draft_ready[\s\S]*?- name: Verify revision produced v2/)?.[0] || "";
  const revisionCheck = workflow.match(/- name: Verify revision produced v2[\s\S]*?- name: Close the exact-user main gate/)?.[0] || "";
  for (const block of [startCheck, revisionCheck]) {
    assert.match(block, /CLOUDFLARE_ACCOUNT_ID: \$\{\{ secrets\.CLOUDFLARE_ACCOUNT_ID \}\}/);
    assert.match(block, /CLOUDFLARE_API_TOKEN: \$\{\{ secrets\.CLOUDFLARE_API_TOKEN \}\}/);
    assert.match(block, /rm -f "\$RUNNER_TEMP\/(?:start|revision)-state-result\.json"/);
    assert.match(block, /QUERY_EXIT=\$\?/);
    assert.match(block, /test "\$QUERY_EXIT" -eq 0 \|\| exit "\$QUERY_EXIT"/);
  }
});

test("full feedback grants are release-bound and use protected Staging WeChat policy values", () => {
  assert.match(workflow, /candidate_commit=process\.env\.GITHUB_SHA/);
  assert.match(workflow, /manifest_hash=process\.env\.STAGING_MANIFEST_HASH/);
  assert.match(workflow, /STAGING_WECHAT_ACCOUNT_BINDING_ID/);
  assert.match(workflow, /STAGING_WECHAT_PROVIDER_BASE_URL/);
  assert.match(workflow, /STAGING_WECHAT_MEDIA_URL_HOSTS/);
  assert.match(workflow, /--account-binding-id "\$STAGING_WECHAT_ACCOUNT_BINDING_ID"/);
  assert.match(workflow, /--provider-base-url "\$STAGING_WECHAT_PROVIDER_BASE_URL"/);
  assert.match(workflow, /--media-url-hosts "\$STAGING_WECHAT_MEDIA_URL_HOSTS"/);
  assert.doesNotMatch(workflow, /WECHAT_APP_ID|WECHAT_APP_SECRET|GITHUB_PAT|FILES_TOKEN/);
});

test("shared phase evidence is redacted and cannot be mistaken for final Issue acceptance", () => {
  assert.match(workflow, /Build redacted phase evidence/);
  assert.match(workflow, /phase_only_not_issue_acceptance/);
  assert.match(workflow, /staging-feedback-audio-canary-\$\{\{ github\.run_id \}\}/);
  const upload = workflow.match(/- name: Upload redacted phase evidence[\s\S]*?- name: Require all temporary grants to be closed/)?.[0] || "";
  assert.ok(upload);
  assert.doesNotMatch(upload, /staging-audio-identity\.json/);
  assert.doesNotMatch(upload, /feedback-canary-grant\.json/);
  assert.doesNotMatch(workflow, /article_content|raw_text|transcript_ref/);
});
